-- config.lua -- shipped defaults.
--
-- Do not edit this file to customise the launcher.  Put your overrides in
--     $PUNKHAZARD_ROOT/config.lua      (default ~/.local/share/punkhazard/config.lua)
-- which is loaded afterwards and merged over these keys, so you only have
-- to state what you want changed:
--
--     return { theme = "amber", crt = false, fullscreen = true }

return {
    width      = 1280,
    height     = 720,
    fullscreen = false,
    vsync      = true,

    -- CRT post-process. The per-effect strengths live in the theme, so a
    -- theme can be flat or heavily curved; this is just the master switch.
    crt        = true,

    show_fps   = false,

    -- Run a game inside the launcher's own window, in the grid area, with
    -- the panels still visible around it.  This is an X11 capability
    -- (XReparentWindow); under Wayland a client cannot embed another
    -- client's surface at all, so there the launcher hides itself and the
    -- game takes the screen instead.  See src/embed.h.
    embed      = true,

    theme      = "hazard",
}
