-- config.lua -- shipped defaults.
--
-- Do not edit this file to customise the launcher.  Put your overrides in
--     $PUNKHAZARD_ROOT/config.lua      (default ~/.local/share/punkhazard/config.lua)
-- which is loaded afterwards and merged over these keys, so you only have
-- to state what you want changed:
--
--     return { theme = "amber", crt = false, fullscreen = true }

return {
    width      = 1280,
    height     = 720,
    fullscreen = false,
    vsync      = true,

    -- CRT post-process. The per-effect strengths live in the theme, so a
    -- theme can be flat or heavily curved; this is just the master switch.
    crt        = true,

    show_fps   = false,
    theme      = "hazard",
}
