/*
 * bin2c -- turn an arbitrary binary file into a C translation unit.
 *
 * Usage: bin2c <symbol> <infile> <outfile>
 *
 * Emits:
 *     const unsigned char <symbol>[]   = { ... };
 *     const unsigned long <symbol>_len = <n>;
 *
 * Why this exists
 * ---------------
 * punkhazard bakes its typeface into the executable so the launcher has no
 * runtime font dependency: no fontconfig, no font path to guess, no failure
 * mode where the UI comes up blank because a file moved.  The font is simply
 * part of .rodata.
 *
 * C has no portable way to include a binary file (C23's #embed is too new to
 * rely on, and ld -b binary is linker-specific), so we generate the array.
 * This is the oldest and most transparent trick in the book: a 60-line
 * program with no dependencies beyond stdio.
 *
 * The output is deliberately plain decimal bytes rather than a string
 * literal -- string literals hit implementation-defined length limits, and
 * C89 only guarantees 509 characters in a literal.  An array of unsigned
 * char has no such limit and every compiler handles it identically.
 */
#include <stdio.h>
#include <stdlib.h>

int
main(int argc, char **argv)
{
	FILE *in, *out;
	int c;
	unsigned long n = 0;

	if (argc != 4) {
		fprintf(stderr, "usage: bin2c <symbol> <infile> <outfile>\n");
		return 2;
	}
	if ((in = fopen(argv[2], "rb")) == NULL) {
		perror(argv[2]);
		return 1;
	}
	if ((out = fopen(argv[3], "wb")) == NULL) {
		perror(argv[3]);
		fclose(in);
		return 1;
	}

	fprintf(out, "/* Generated by tools/bin2c from %s -- do not edit. */\n",
	    argv[2]);
	fprintf(out, "const unsigned char %s[] = {\n", argv[1]);

	while ((c = getc(in)) != EOF) {
		/* 16 bytes per line keeps the generated file diffable and
		 * keeps individual lines short enough for any compiler. */
		fprintf(out, "%d,", c);
		if ((++n & 15u) == 0)
			putc('\n', out);
	}

	fprintf(out, "\n};\n");
	fprintf(out, "const unsigned long %s_len = %luUL;\n", argv[1], n);

	if (ferror(in) || ferror(out)) {
		fprintf(stderr, "bin2c: I/O error\n");
		fclose(in);
		fclose(out);
		return 1;
	}
	fclose(in);
	if (fclose(out) != 0) {
		perror(argv[3]);
		return 1;
	}
	fprintf(stderr, "bin2c: %s <- %s (%lu bytes)\n", argv[3], argv[2], n);
	return 0;
}
